server:  
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: mariadb://mariadb:3306/adega
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    web: ERROR
    org:
      springframework:
        security: DEBUG
        web:
          cors: ERROR

data:
  produto: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/produtos-mnboX5IPl6VgG390FECTKqHsD9SkLS.json
  cliente: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/clientes-Vz1U6aR3GTsjb3W8BRJhcNKmA81pVh.json
