spring:
  profiles:
    active: local
  application:
    name: digio-adega
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /adega